name: money_app
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  fl_chart: ^0.12.3
  intl: ^0.17.0
  provider: ^4.3.3
  shared_preferences: ^2.0.7
  http: ^0.13.3
  flutter_easyloading: ^3.0.0
  get_it: ^7.2.0
  stacked_services: ^0.8.13
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.2
  firebase_auth: ^3.1.1
  font_awesome_flutter: ^9.1.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"