name: moneylover
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  carousel_slider: ^4.1.1
  flutter_svg: ^1.1.4
  intl: ^0.17.0
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  get_storage: ^2.0.3
  flutter_local_notifications: ^9.8.0+1
  firebase_messaging: ^13.0.0

# Uncomment to generate model (build_runners)
# dependency_overrides:
#   analyzer: ^1.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_flavorizr: ^2.1.4
  build_runner: 1.11.5
  json_serializable: 3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# terminal: flutter pub run flutter_flavorizr
flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    production:
      app:
        name: "Money Lover"

      android:
        applicationId: "com.moneylover.mobile"
        icon: "assets/images/app_icon.png"
        firebase:
          config: ".firebase/production/google-services.json"

      ios:
        bundleId: "com.moneylover.mobile"
        icon: "assets/images/app_icon.png"
        firebase:
          config: ".firebase/production/GoogleService-Info.plist"

    staging:
      app:
        name: "STG Money Lover"

      android:
        applicationId: "com.moneylover.mobile.staging"
        icon: "assets/images/app_icon.png"
        firebase:
          config: ".firebase/staging/google-services.json"

      ios:
        bundleId: "com.moneylover.mobile.staging"
        icon: "assets/images/app_icon.png"
        firebase:
          config: ".firebase/staging/GoogleService-Info.plist"
